---
version: '3.5'

services:
  okbr-serenata-notebooks:
    container_name: okbr-serenata-notebooks
    build: .
    networks:
      - frontend
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/notebooks
      - ./data:/notebooks/data
    command:
      - "jupyter"
      - "notebook"
      - "--ip=0.0.0.0"
      - "--port=8888"
      - "--no-browser"
      - "--allow-root"

networks:
  frontend:
    name: okbr-serenata-notebooks
